name: regional_cbnrm
description: "Mobile companion app for Wildlife Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  get: ^4.6.5

  # HTTP and API
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1

  # Local storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0

  # UI components
  intl: 0.19.0

  # Authentication
  flutter_secure_storage: ^8.0.0

  # Utils
  connectivity_plus: ^4.0.2
  logger: ^2.5.0
  path: ^1.8.3
  uuid: ^3.0.7
  device_info_plus: ^9.0.3
  flutter_local_notifications: ^14.0.0

  # Maps and location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Form builder
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - resource_africa_sqlite_migration.sql

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
