#!/bin/bash
echo "Resource Africa App Launch Script"
echo "================================="
echo ""
echo "This script provides steps to run the app on emulator or physical device."
echo ""
echo "Instructions for running the app:"
echo "1. Make sure you have Flutter SDK installed and available in your PATH"
echo "2. Make sure you have an emulator running or a physical device connected"
echo "3. Run the following command in this directory:"
echo ""
echo "   flutter run --verbose"
echo ""
echo "If you encounter any issues:"
echo "- Check that the Flutter SDK is properly installed"
echo "- Ensure your emulator is running or device is connected"
echo "- If there are compilation errors, check the specific error message"
echo ""
echo "For the Poaching Module implementation:"
echo "- Navigate to /poaching-incidents from the dashboard"
echo "- This will show the list of poaching incidents"
echo "- Tap the + button to create a new incident"
echo "- Tap on an incident to see details"
echo "- Use the FAB in the details screen to add poachers"
echo ""
echo "Attempting to run Flutter commands:"
command -v flutter >/dev/null 2>&1 && flutter doctor -v || echo "Flutter not found in PATH"